<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PoliceOverhaulVI</AssemblyName>
    <RootNamespace>VOX.PoliceOverhaulVI</RootNamespace>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyVersion>0.7.0.0</AssemblyVersion>
    <FileVersion>0.7.0.0</FileVersion>
    <Version>0.7.0</Version>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>true</Optimize>
    <Deterministic>true</Deterministic>
    <ScriptHookVDotNet3Path Condition="'$(ScriptHookVDotNet3Path)' == ''">refs/ScriptHookVDotNet3.dll</ScriptHookVDotNet3Path>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <Reference Include="ScriptHookVDotNet3"><HintPath>$(ScriptHookVDotNet3Path)</HintPath><Private>False</Private></Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Drawing" />
  </ItemGroup>
</Project>
