@echo off
setlocal EnableExtensions
title VOX RDR2 RPF8 Research Profiler v0.5.0
cd /d "%~dp0"

echo ============================================================
echo   VOX RDR2 RPF8 Research Profiler v0.5.0
echo ============================================================
echo.
echo READ-ONLY POST-PROCESSOR.
echo It reads the CSV reports generated by the TFIT2 bridge.
echo It does NOT read or extract RDR2 game assets.
echo.

set "CAT=%~1"
if not defined CAT (
  if exist "%~dp0VOX-RDR2-TFIT2-Catalog\RPF8-decrypted-entries.csv" (
    set "CAT=%~dp0VOX-RDR2-TFIT2-Catalog"
  ) else (
    set /p "CAT=Folder containing RPF8-decrypted-entries.csv: "
  )
)
set "CAT=%CAT:"=%"
if not exist "%CAT%\RPF8-decrypted-entries.csv" (
  echo.
  echo [ERROR] RPF8-decrypted-entries.csv not found in:
  echo %CAT%
  echo.
  pause
  exit /b 1
)

set "TMPDIR=%TEMP%\VOX_RDR2_PROFILE_%RANDOM%_%RANDOM%"
set "ZIP=%TMPDIR%\rdr3_discoveries.zip"
set "KNOW=%TMPDIR%\knowledge"
mkdir "%TMPDIR%" >nul 2>&1
mkdir "%KNOW%" >nul 2>&1

echo [1/3] Fetching pinned public RDR2 knowledge base...
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference='Stop'; $ProgressPreference='SilentlyContinue';" ^
  "Invoke-WebRequest -UseBasicParsing -Headers @{'User-Agent'='VOX-RDR2-Profiler'} -Uri 'https://github.com/femga/rdr3_discoveries/archive/49087fb2756594d2364e4abf79ee1df44d6ef3b4.zip' -OutFile '%ZIP%';" ^
  "Expand-Archive -Path '%ZIP%' -DestinationPath '%KNOW%' -Force"
set "FETCHRC=%ERRORLEVEL%"

if "%FETCHRC%"=="0" (
  for /d %%D in ("%KNOW%\rdr3_discoveries-*") do set "KNOWROOT=%%~fD"
  echo [2/3] Public knowledge base ready.
) else (
  echo [WARNING] Public knowledge download failed. Running structural profile only.
  set "KNOWROOT="
)

echo [3/3] Profiling extensions, encryption, hashes and project priorities...
if defined KNOWROOT (
  "VOX-RDR2-RPF8-Research-Profiler.exe" --entries "%CAT%\RPF8-decrypted-entries.csv" --archives "%CAT%\RPF8-decrypted-archives.csv" --knowledge "%KNOWROOT%" --out "%~dp0VOX-RDR2-RPF8-Research-Profile"
) else (
  "VOX-RDR2-RPF8-Research-Profiler.exe" --entries "%CAT%\RPF8-decrypted-entries.csv" --archives "%CAT%\RPF8-decrypted-archives.csv" --out "%~dp0VOX-RDR2-RPF8-Research-Profile"
)
set "RC=%ERRORLEVEL%"
rd /s /q "%TMPDIR%" >nul 2>&1

echo.
if "%RC%"=="0" (
  echo [OK] Research profile completed.
  echo Send PROFILE-summary.txt, PROFILE-summary.json,
  echo PROFILE-resolved-names.csv and PROFILE-priority-candidates.csv.
) else (
  echo [ERROR] Profiler returned exit code %RC%.
)
echo Output: %~dp0VOX-RDR2-RPF8-Research-Profile
echo.
pause
exit /b %RC%
